[profile.default]
src = "src"
test = "test"
libs = ["node_modules"]
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "ds-test/=node_modules/ds-test/src/",
  "sstore2/=node_modules/@0xsequence/sstore2/contracts/",
  "create3/=node_modules/@0xsequence/create3/contracts/",
]
gas_report = []
